### PR TITLE
Update Operations#Source to inherit from providers common to gain error handling

### PR DESCRIPTION
**Pull request by lindgrenj6**
This will allow us to pull in the error handling that is now provided in the common gem.

### CODE REVIEW

**Comment by lindgrenj6** [comment]
@syncrou @slemrmartin this is ready for review, tested on CI which even though those are all unavailable it is working :+1:

**Review by syncrou — APPROVED** [review]
This LGTM 👍 - very happy to bring everything in line with the common checking.

**Comment by syncrou** [comment]
@slemrmartin if you could take a look, that would be great.

**Review by slemrmartin — COMMENTED** [review]
@lindgrenj6 
the providers-common on-premise check is missing the connection status (should be also implemented for on-premise tower check). I'm working on similar change in #15 

Also I'm not sure if this change will keep the same error messages (providers-common has less number of error messages) and these are written in some documentation.

**Comment by lindgrenj6** [comment]
@slemrmartin yes I know the error messages are inconsistent (as of now) but this is more to get the error handling pushed up - we are running into the same issue again on prod with a bad deleted source and the entire worker is unable to process any messages. 

The messages should stay the same in this class since we're overriding the subclass' `ERROR_MESSAGES` field, so that should be fine.

**Review by syncrou — APPROVED** [review]
LGTM 👍 

@slemrmartin, we're trying to solve the error handling problem on Prod / Stage with Sources so I needed to get this in.

I see that https://github.com/RedHatInsights/topological_inventory-satellite/pull/15 is in WIP yet, but also pulls in some of the changes from this PR. I believe once #15 is ready it can be rebased from these changes and we can get your refactor fully in.

**Pull request merged**
